trigger:
- master

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest
  # name: myAdoAgentForSynopsysAndDSi
  # demands:
  #  - agent.name -equals myAdoAgentForSynopsysAndDSi
  
variables:
  - group: Polaris
  # - name: System.Debug
  #   value: true
  

steps:

- task: SynopsysSecurityScan@1.7.117
  displayName: 'Polaris Scan'
  ### Use below configuration to set specific detect environment variables
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
  inputs:

    # BLACKDUCK_URL: "test"
    # BLACKDUCK_TOKEN: "test"
    ### Accepts Multiple Values
    #BLACKDUCK_SCAN_FAILURE_SEVERITIES: 'BLOCKER,CRITICAL'
    ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
    # BLACKDUCK_FIXPR_ENABLED: true
    #BLACKDUCK_FIXPR_FILTER_SEVERITIES: "CRITICAL,  HIGH"
    #BLACKDUCK_FIXPR_MAXCOUNT: 2
    #BLACKDUCK_FIXPR_USEUPGRADEGUIDANCE: 'SHORT_TERM,LONG_TERM'
    # BLACKDUCK_PRCOMMENT_ENABLED: true
    
    POLARIS_SERVER_URL: $(POLARIS_URL)
    POLARIS_ACCESS_TOKEN: $(POLARIS_TOKEN)
    POLARIS_APPLICATION_NAME: "E2E-Integration-App"
    POLARIS_PROJECT_NAME: "TestProject"
    POLARIS_ASSESSMENT_TYPES: 'SCA' 
    MARK_BUILD_STATUS: 'SUCCEEDED'
   
    # POLARIS_ASSESSMENT_MODE: "SOURCE_UPLOAD"
    # PROJECT_DIRECTORY: "/home/maruf/nodegoat"
    # PROJECT_SOURCE_ARCHIVE: "/home/maruf/nodegoat.zip"
    # PROJECT_SOURCE_EXCLUDES: ".git, .gitignore"
    # PROJECT_SOURCE_PRESERVESYMLINKS: false


    # polaris_server_url: "$(POLARIS_URL)"
    # polaris_access_token: "$(POLARIS_TOKEN)"
    # polaris_assessment_types: "SAST,SCA"
    # polaris_application_name: "test_ado"
    # polaris_project_name: "test_ado"

    # POLARIS_ASSESSMENT_MODE: "SOURCE_UPLOAD"
    # PROJECT_DIRECTORY: "/home/maruf/nodegoat"
    # PROJECT_SOURCE_ARCHIVE: "/home/maruf/nodegoat.zip"
    # PROJECT_SOURCE_EXCLUDES: ".git, .git"

    # AZURE_TOKEN: $(AZURE_TOKEN) # Mandatory when BRIDGE_BLACKDUCK_AUTOMATION_PRCOMMENT is set to 'true'

    ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
    #INCLUDE_DIAGNOSTICS: true
    #SYNOPSYS_BRIDGE_INSTALL_DIRECTORY: $(SYNOPSYS_BRIDGE_INSTALL_DIRECTORY)
